name: Release
on:
  push:
    branches:
      - prod
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run lint:check

      - name: Run tests
        run: npx nyc npm run test

      - uses: actions/upload-artifact@master
        with:
          name: coverage-lcov
          path: coverage

      - name: Build
        run: npm run build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  sonarcube:
    runs-on: ubuntu-latest
    needs: release
    concurrency:
      group: ${{ github.ref }}-sonarcube
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/download-artifact@master
        with:
          name: coverage-lcov
          path: coverage

      - name: Get npm package version
        id: package-version
        uses: Saionaro/extract-package-version@v1.1.1

      - uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_CLOUD_TOKEN }}
        with:
          args: >
            -Dsonar.projectVersion=${{ steps.package-version.outputs.version }}
